server:
  port: 3000
application:
  domain: chicken-sh.op
  name: 'The Kernels Chicken Shop'
  logo: KFC-logo.png
  favicon: kfc-favicon.ico
  numberOfRandomFakeUsers: 0
  showChallengeSolvedNotifications: true
  showChallengeHints: true
  showVersionNumber: true
  theme: deeporange-indigo # Options: bluegrey-lightgreen blue-lightblue deeppurple-amber indigo-pink pink-bluegrey purple-green deeporange-indigo
  gitHubRibbon: false
  twitterUrl: 'https://twitter.com/KFCAustralia'
  facebookUrl: 'https://www.facebook.com/KFCAustralia'
  slackUrl: 'https://sectalks.slack.com/'
  redditUrl: 'https://www.reddit.com/r/kfc/'
  pressKitUrl: 'https://github.com/OWASP/owasp-swag/tree/master/projects/juice-shop'
  planetOverlayMap: orangemap2k.jpg
  planetName: Kentucky
  recyclePage:
    topProductImage: recycle_top.jpg
    bottomProductImage: recycle_bottom.jpg
  altcoinName: Zingercoin
  cookieConsent:
    backgroundColor: '#E4002B'
    textColor: '#ffffff'
    buttonColor: '#ffffff'
    buttonTextColor: '##E4002B'
    message: 'This website uses cookies to ensure you get a finger licking good experience.'
    dismissText: 'Me want it!'
    linkText: 'But me wait!'
    linkUrl: 'https://www.youtube.com/watch?v=9PnbKL3wuH4'
  securityTxt:
    contact: 'mailto:donotreply@owasp-juice.shop'
    encryption: 'https://keybase.io/bkimminich/pgp_keys.asc?fingerprint=19c01cb7157e4645e9e2c863062a85a8cbfbdcda'
    acknowledgements: '/#/score-board'
challenges:
  safetyOverride: false
  overwriteUrlForProductTamperingChallenge: 'https://owasp.slack.com'
products:
  -
    name: 'Favourites Box'
    price: 12.75
    description: 'It’s Ok To Play Favourites. Sometimes.'
    image: favourites_box.jpg
    reviews: # Options 'author': admin, jimmy.k, bender, ciso, support, morty, mc.safesearch
      - { text: 'One of my favorites!', author: admin }
  -
    name: '3 Piece Box'
    description: 'ALL. OF. THIS.'
    price: 11.75
    image: 3_piece_box.jpg
  -
    name: 'Original Tenders Box'
    description: 'Dip It Real Good.'
    price: 11.45
    image: original_tenders_box.jpg
    reviews:
      - { text: 'I bought it, would buy again. 5/7', author: admin }
  -
    name: 'Ultimate Box'
    description: 'No Regrets.'
    price: 10.95
    image: ultimate_box.jpg
  -
    name: 'Twister Box'
    description: 'Wrap It Up, People.'
    price: 12.45
    image: original_twister_box.jpg
    reviews:
      - { text: 'Fry liked it too.', author: bender }
  -
    name: 'Sweet Chilli Twister Box'
    description: 'Sweet, Dude...'
    price: 12.45
    image: sweet_chili_twister_box.jpg
  -
    name: 'Honey Mustard Twister Box'
    description: 'Honey, We Made A Twister.'
    price: 12.45
    image: honey_mustard_twister_box.jpg
  -
    name: 'Ceasar Twister Box'
    description: 'Like A Caesar Salad, But Less Salady.'
    price: 12.45
    image: ceasar_twister_box.jpg
  -
    name: 'Zinger Stacker Combo'
    description: 'Hit Your Hunger For Six With The KFC Zinger Stacker.'
    price: 11.65
    image: zinger_stacker_combo.jpg
    urlForProductTamperingChallenge: 'https://the-colonels-chicken-shop.herokuapp.com'
  -
    name: 'Fillet Burger Combo'
    description: 'The OG.'
    price: 9.15
    image: fillet_burger_combo.jpg
    useForChristmasSpecialChallenge: true
  -
    name: 'Kentucky Burger Combo'
    description: 'No Seriously You Have To Try This. <br/><span style="color:red;">This item has been made unavailable due to breaches in food safety standards.</span>'
    price: 10.95
    image: undefined.jpg
    keywordsForPastebinDataLeakChallenge:
      - Monosodium Glutamate
      - Hydrogen Peroxide
  -
    name: 'Szechuan Sauce'
    description: 'A Flavour Explosion. By now this is a rare collectors item. <em>Out of stock!</em>'
    price: 999.99
    image: szechuan_sauce.png
    deletedDate: '2017-10-07'
  -
    name: 'Bacon & Cheese Combo'
    description: 'Chicken, Cheese, Bacon Combo! Enough Said.'
    price: 9.95
    image: bacon_cheese_combo.jpg
  -
    name: 'Popcorn Chicken Bucket (10pcs)'
    description: 'Tender. Tantalising. Yours For The Taking!'
    price: 10.00
    image: popcorn_chicken.jpg
  -
    name: '1 Piece of Chicken'
    description: 'Our Irresistible, Unmistakable Original Recipe Chicken.'
    price: 3.00
    image: 1_piece.jpg
    # Exif metadata contains "OpenSCAD" as subtle hint...
    fileForRetrieveBlueprintChallenge: JuiceShop.stl # ...to blueprint file type
  -
    name: '5 Pieces of Chicken'
    description: '5 Piece Original Recipe'
    price: 13.40
    image: 5_piece.jpg
  -
    name: '3 Wicked Wings'
    description: 'Spice Up Your Life.'
    price: 3.95
    image: 3_wicked.jpg
    reviews:
      - { text: 'I straight-up gots nuff props fo''these wings!', author: mc.safesearch }
  -
    name: '6 Wicked Wings'
    description: 'What’s Better Than 3 Wicked Wings? 6 Of Course.'
    price: 6.95
    image: 6_wicked.jpg
  -
    name: '10 Wicked Wings'
    description: 'A Perfect Addition To Any Meal.'
    price: 10.95
    image: 10_wicked.jpg
  -
    name: 'Regular Seasoned Chips'
    description: 'The Chips You Love.'
    price: 3.25
    image: regular_chips.jpg
    reviews:
      - { text: 'These chips got it going on!', author: mc.safesearch }
      - { text: 'These, chips, are, highly, satisfying.', author: jimmy.k }
  -
    name: 'Honey Mustard Shaker Salad'
    description: 'Mustard… Ohh Honey, Honey.'
    price: 4.95
    image: honey_mustard_salad.jpg
  -
    name: 'Large Potato & Gravy'
    description: 'Have You Ever Tried Dipping With This Bad Boy?'
    price: 5.95
    image: potato_gravy.jpg
    reviews:
      - { text: 'Fresh out of a replicator.', author: jimmy.k }
  -
    name: 'Large Coleslaw'
    description: 'Cool, Crispy, Crunchy.'
    price: 5.95
    image: coleslaw.jpg
  -
    name: 'Chocolate Mousse'
    description: 'Finish With A Sweet Treat. Packaging can be <a href="/#recycle">sent back to us</a> for recycling.'
    price: 2.50
    image: chocolate_mousse.jpg
  -
    name: 'Craft Dipping Sauces'
    description: 'What’s Your Flavour? These rare sauces were designed and handcrafted in Sweden.'
    price: 0.50
    image: dipping_sauces.jpg 
    reviews: 
      - { text: 'Good God! I spilt some, on my Starfleet issued, uniform, and nothing will, get it out.', author: jimmy.k }

ctf:
  showFlagsInNotifications: false
  showCountryDetailsInNotifications: none # Options: none  name  flag  both
  countryMapping: ~
